Repository crashmax-dev/fireworks-js, pull requests merged in 2022-10, with the labels that each got.

#78 feat: added `useImperativeHandle` for `react`, `preact` packages
  README.md
  examples/with-preact/src/App.tsx
  examples/with-preact/src/index.tsx
  examples/with-react/src/App.tsx
  examples/with-react/src/index.tsx
  packages/preact/src/index.tsx
  packages/react/src/index.tsx
Labels: enhancement, hacktoberfest-accepted, v2.x, package

#79 feat: added `waitStop` #76
  README.md
  examples/basic/src/index.ts
  packages/fireworks-js/src/fireworks.ts
Labels: enhancement, hacktoberfest-accepted, v2.x

#80 feat: reduce size with esnext target
  packages/fireworks-js/src/fireworks.ts
  packages/fireworks-js/src/vite-env.d.ts
  packages/fireworks-js/tsconfig.json
  packages/fireworks-js/vite.config.ts
  packages/preact/vite.config.ts
  packages/react/vite.config.ts
  packages/vue/vite.config.ts
  packages/web/vite.config.ts
Labels: bug, enhancement, hacktoberfest-accepted, v2.x

#81 refactor(packages/angular): ng directive
  examples/with-angular/package.json
  examples/with-angular/src/app/app.component.css
  examples/with-angular/src/app/app.component.html
  examples/with-angular/src/app/app.component.ts
  examples/with-angular/src/favicon.ico
  examples/with-angular/src/index.html
  examples/with-angular/src/styles.css
  package.json
  packages/angular/package.json
  packages/angular/projects/ng-fireworks/package.json
  packages/angular/projects/ng-fireworks/src/lib/ng-fireworks.component.ts
  packages/angular/projects/ng-fireworks/src/lib/ng-fireworks.directive.ts
  packages/angular/projects/ng-fireworks/src/lib/ng-fireworks.module.ts
  packages/angular/projects/ng-fireworks/src/public-api.ts
  pnpm-lock.yaml
Labels: enhancement, hacktoberfest-accepted, v2.x, package

#83 refactor(packages/svelte): reinit svelte proejct, bump dependencies
  examples/basic/package.json
  examples/with-angular/package.json
  examples/with-preact/package.json
  examples/with-react/package.json
  examples/with-solid/package.json
  examples/with-svelte/package.json
  examples/with-vue/package.json
  examples/with-web-components/package.json
  package.json
  packages/preact/package.json
  packages/solid/package.json
  packages/svelte/package.json
  packages/svelte/src/app.d.ts
  packages/svelte/src/app.html
  packages/svelte/src/lib/fireworks.svelte
  packages/svelte/src/routes/+page.svelte
  packages/svelte/src/shim.d.ts
  packages/svelte/svelte.config.js
  packages/svelte/vite.config.ts
  packages/web/package.json
  packages/web/src/index.ts
  pnpm-lock.yaml
  turbo.json
  website/package.json
Labels: enhancement, hacktoberfest-accepted, v2.x, package

#84 use pointer events
  packages/fireworks-js/src/mouse.ts
Labels: enhancement, hacktoberfest-accepted, v2.x

#85 feat: raf fps property
  README.md
  packages/fireworks-js/src/fireworks.ts
  packages/fireworks-js/src/options.ts
  packages/fireworks-js/src/raf.ts
  packages/fireworks-js/src/types.ts
  website/src/config.ts
  website/src/index.ts
Labels: enhancement, hacktoberfest-accepted, v2.x
